config/routes.rb
Recipeapp::Application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  post "login" => "sessions#create"
  get "signup" => "users#new", :as => "signup"

  get "sessions/logout"

  resources :users

  resources :recipe_ingredient_quantities

  resources :ingredient_quantities

  resources :quantities

  resources :recipe_ingredients

  resources :recipes

  resources :ingredients

  root :to => 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :description, :name, :recipe_ingredients_attributes
  
  has_many :recipe_ingredients, :dependent => :destroy
  
  accepts_nested_attributes_for :recipe_ingredients,  
  								:allow_destroy => true,
  								:reject_if => lambda { |a| a[:name].blank? || a[:amount].blank? }
  

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])
   
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="control-group">
      <div class="controls btn">
        <%= link_to_add_fields( "Add Recipe Ingredient", f, :recipe_ingredients) %>
     </div>
  </div>
  
  <div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recipes_path, :class => 'btn' %>
    </div>
  </div>

  
<% end %>

app/views/recipes/_recipe_ingredient_fields.html.erb
    
    <fieldset class='fields'>
      <div class='controls'>
        <h2> Ingredient </h2>

      </div>
      <div class='control-group'>
        <%= f.label :ingredient, :class => 'control-label'%>

        <div class="controls">
          <%= f.text_field :name, :class => 'text_field' %>
        </div>
      </div>

      <div class='control-group'>
        <%= f.label :quantity, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :amount, :class => 'text_field'%>
        </div>
      </div>
    
      <div class="form-actions">
        <div class="btn">
         <%= link_to_remove_fields( "remove ingredient", f )%>
       </div> 
      </div>
  </fieldset>

app/views/recipes/edit.html.erb
<%- model_class = @recipe.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<%- model_class = Recipe.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <div style = "margin-top:10px;">
  <%= link_to t(".new", :default => t("helpers.links.add_new_recipe")),
            new_recipe_path,
            :class => 'btn btn-primary' %>
  </div>  
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>
        <td><%= recipe.description %></td>
        <td><%=l recipe.created_at %></td>
        <td>

          <%= link_to t('.show', :default => t("helpers.links.show")),
                      recipe_path(recipe), :class => 'btn btn-mini btn-info' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_recipe_path(recipe), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      recipe_path(recipe),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/new.html.erb
<%- model_class = @recipe.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<%- model_class = @recipe.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @recipe.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @recipe.description %></dd>
</dl>



<p> <b>Ingredients: </b> </p> 
<ul>
<% @recipe.recipe_ingredients.each do |ingredient| %>
  <li> <%= ingredient.amount %> : <%= ingredient.name %> </li>
<%end%>
</ul>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              recipes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recipe_path(@recipe), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recipe_path(@recipe),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>