config/routes.rb
Recipeapp::Application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  post "login" => "sessions#create"
  get "signup" => "users#new", :as => "signup"

  get "sessions/logout"

  resources :users

  resources :recipe_ingredient_quantities

  resources :ingredient_quantities

  resources :quantities

  resources :recipe_ingredients

  resources :recipes

  resources :ingredients

  root :to => 'recipes#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  

  attr_accessible :name, :recipe_ingredients_attributes

  has_many :recipe_ingredients
  has_many :recipes, :through => :recipe_ingredients

  accepts_nested_attributes_for :recipe_ingredients

  before_save :normalize

private

  def normalize
    self.name = self.name.downcase.strip if self.name
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.name %></td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ingredient.name %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>