config/routes.rb
Recipeapp::Application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  post "login" => "sessions#create"
  get "signup" => "users#new", :as => "signup"

  get "sessions/logout"

  resources :users

  resources :recipe_ingredient_quantities

  resources :ingredient_quantities

  resources :quantities

  resources :recipe_ingredients

  resources :recipes

  resources :ingredients

  root :to => 'recipes#index'

end

app/helpers/recipe_ingredient_quantities_helper.rb
module RecipeIngredientQuantitiesHelper
end

app/views/recipe_ingredient_quantities/_form.html.erb
<%= form_for(@recipe_ingredient_quantity) do |f| %>
  <% if @recipe_ingredient_quantity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_ingredient_quantity.errors.count, "error") %> prohibited this recipe_ingredient_quantity from being saved:</h2>

      <ul>
      <% @recipe_ingredient_quantity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_ingredient_id %><br />
    <%= f.number_field :recipe_ingredient_id %>
  </div>
  <div class="field">
    <%= f.label :quantity_id %><br />
    <%= f.number_field :quantity_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_ingredient_quantities/edit.html.erb
<h1>Editing recipe_ingredient_quantity</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe_ingredient_quantity %> |
<%= link_to 'Back', recipe_ingredient_quantities_path %>

app/views/recipe_ingredient_quantities/index.html.erb
<h1>Listing recipe_ingredient_quantities</h1>

<table>
  <tr>
    <th>Recipe ingredient</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipe_ingredient_quantities.each do |recipe_ingredient_quantity| %>
  <tr>
    <td><%= recipe_ingredient_quantity.recipe_ingredient_id %></td>
    <td><%= recipe_ingredient_quantity.quantity_id %></td>
    <td><%= link_to 'Show', recipe_ingredient_quantity %></td>
    <td><%= link_to 'Edit', edit_recipe_ingredient_quantity_path(recipe_ingredient_quantity) %></td>
    <td><%= link_to 'Destroy', recipe_ingredient_quantity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe ingredient quantity', new_recipe_ingredient_quantity_path %>

app/views/recipe_ingredient_quantities/new.html.erb
<h1>New recipe_ingredient_quantity</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_ingredient_quantities_path %>

app/views/recipe_ingredient_quantities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipe ingredient:</b>
  <%= @recipe_ingredient_quantity.recipe_ingredient_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @recipe_ingredient_quantity.quantity_id %>
</p>


<%= link_to 'Edit', edit_recipe_ingredient_quantity_path(@recipe_ingredient_quantity) %> |
<%= link_to 'Back', recipe_ingredient_quantities_path %>